#!/bin/bash -e

# patch cloud-init's user-data file in case the imager messed up
# (this may happen with authorized_keys files instead of id_*.pub files,
# as authorized_keys may contain multiple keys, but the imager currently
# fails to handle those)
sed -e 's/^ssh-/    - ssh-/g' -i $MOUNTPOINT/boot/firmware/user-data

# disable password authentication (add parameter disabling it after the "enable_ssh: true" line)
sed -e '/enable_ssh: true /a ssh_pwauth: false' -i $MOUNTPOINT/boot/firmware/user-data
