#!/bin/bash -e

echo "Adding boot partition chooser (autoboot.txt) to first partition ..."
# add boot partition chooser config file
echo "[all]" >> $MOUNTPOINT/boot/firmware/autoboot.txt
echo "boot_partition=1" >> $MOUNTPOINT/boot/firmware/autoboot.txt
