#!/bin/bash -e

# set and generate locale so the following update steps won't complain
sed -e 's/^en_GB/# en_GB/' \
    -e "s/^# $OUR_LOCALE/$OUR_LOCALE/" \
    -i $MOUNTPOINT/etc/locale.gen
sed -e 's/=en_GB/='${OUR_LOCALE%%.}'/' -i $MOUNTPOINT/etc/locale.conf
chroot $MOUNTPOINT locale-gen
