#!/bin/bash -e

# update package list, install etckeeper so we get a log of our upcoming changes
chroot $MOUNTPOINT apt-get update
chroot $MOUNTPOINT apt-get install -y etckeeper

# install all upgrades and clean up afterwards
chroot $MOUNTPOINT apt-get upgrade -d -y
chroot $MOUNTPOINT apt-get upgrade -y
chroot $MOUNTPOINT apt-get full-upgrade -d -y
chroot $MOUNTPOINT apt-get full-upgrade -y
chroot $MOUNTPOINT apt-get clean
chroot $MOUNTPOINT apt-get autopurge -y

# install the minimum required packages
chroot $MOUNTPOINT apt-get install -y ifupdown bridge-utils screen git vim
