#!/bin/bash -e

# check for custom install scripts; execute it if present, and remove the executable bit afterwards (so it runs only once)

# Note that since ENV1 will be cloned to ENV2 and ENV3, ENV1-custom-install.sh is actually more of an ENVALL than an ENV1 custom script

if ! [ -f ../custom/ENV1-custom-install.sh ] ; then
	echo "No custom file found, using template from template directory."
	cp ../templates/ENV1-custom-install.sh ../custom/
fi
if bash -n ../custom/ENV1-custom-install.sh ; then
	echo "A syntactically correct custom install file for ENV1 has been detected. Executing in changeroot ..."
	rsync -aPvH ../custom/ENV1-custom-install.sh $MOUNTPOINT/ENV1-custom-install.sh && \
	chmod +x $MOUNTPOINT/ENV1-custom-install.sh
	chroot $MOUNTPOINT ./ENV1-custom-install.sh && \
	chmod -x $MOUNTPOINT/ENV1-custom-install.sh
elif ! bash -n ../custom/ENV1-custom-install.sh ; then
	echo "Syntax error in ./ENV1-custom-install.sh detected. Skipping, but continuing ..."
	mv $MOUNTPOINT/ENV1-custom-install.sh $MOUNTPOINT/ENV1-custom-install.broken
	exit 0
else
	echo "No custom install file for ENV1 found, continuing ..."
	exit 0
fi
