#!/bin/bash -e

# check for custom install scripts; execute it if present, and remove the executable bit afterwards (so it runs only once)

# Note that since ENV1 will be cloned to ENV2 and ENV3, ENV1-custom-install.sh is actually more of an ENVALL than an ENV1 custom script

if ! [ -x ./custom/ENV1-custom-install.sh ] ; then
	echo "No executable custom file found, using template from template directory."
	cp ./templates/ENV1-custom-install.sh ./custom/
	chmod +x ./custom/ENV1-custom-install.sh
	ENV1_NO_CUSTOM=true
fi
if bash -n ./custom/ENV1-custom-install.sh ; then
	echo "A syntactically correct custom install file for ENV1 has been detected. Executing in changeroot ..."
	rsync -aPvH ./custom/ENV1-custom-install.sh $MOUNTPOINT/ENV1-custom-install.sh && \
	chroot $MOUNTPOINT ./ENV1-custom-install.sh && \
	chmod -x $MOUNTPOINT/ENV1-custom-install.sh
elif ! bash -n ./custom/ENV1-custom-install.sh ; then
	echo "Syntax error in ENV1-custom-install.sh detected. Skipping, but continuing ..."
	mv $MOUNTPOINT/ENV1-custom-install.sh $MOUNTPOINT/ENV1-custom-install.broken
fi
if [ -n "$ENV1_NO_CUSTOM" ]; then
	rm ./custom/ENV1-custom-install.sh
fi
exit 0
