#!/bin/bash -e

# check for custom install script; execute it if present, and remove the executable bit afterwards (so it runs only once)
test -x ./ENV2-custom-install.sh && rsync -aPvH ./ENV2-custom-install.sh $MOUNTPOINT/ENV2-custom-install.sh && chroot $MOUNTPOINT ./ENV2-custom-install.sh && chmod -x $MOUNTPOINT/ENV2-custom-install.sh
