#!/bin/bash -e

# now we are cloning ENV1 rootfs to ENV3 rootfs
echo "Cloning ENV1's rootfs to ENV3's rootfs ..."
while ! dd if=$PARTFIVE of=$PARTSEVEN bs=4096k status=progress; do sleep 1; done

# check if write to block device really succeeded
if [ -b $PARTSEVEN ]; then
	echo "Cloning complete."
else
	echo "Error: Device $PARTSEVEN is no longer a block device! Aborting."
	exit 1
fi

echo "Changing partition label to rootfs2 and assigning new UUID ..."
# to make sure we can tell our clones apart, we set a new LABEL and UUID
tune2fs -L rootfs3 -U $(uuid) $PARTSEVEN

# sync changes
sync
