#!/bin/bash -e

# check for custom install script; execute it if present, and remove the executable bit afterwards (so it runs only once)
if [ -x ./ENV3-custom-install.sh ] && bash -n ./ENV3-custom-install.sh ; then
	rsync -aPvH ./ENV3-custom-install.sh $MOUNTPOINT/ENV3-custom-install.sh && \
	chroot $MOUNTPOINT ./ENV3-custom-install.sh && \
	chmod -x $MOUNTPOINT/ENV3-custom-install.sh
elif [ -x ./ENV3-custom-install.sh ] && ! bash -n ./ENV3-custom-install.sh ; then
	echo "Syntax error in ./ENV3-custom-install.sh detected. Skipping, but continuing ..."
	exit 0
else
	echo "No custom install file found, continuing ..."
	exit 0
fi
