#!/bin/bash -e

# check for custom install script; execute it if present, and remove the executable bit afterwards (so it runs only once)

if ! [ -f ../custom/ENV3-custom-install.sh ] ; then
	cp ../templates/ENV3-custom-install.sh ../custom/
fi
if bash -n ../custom/ENV3-custom-install.sh ; then
	echo "A syntactically correct custom install file for ENV3 has been detected. Executing in changeroot ..."
	rsync -aPvH ../custom/ENV3-custom-install.sh $MOUNTPOINT/ENV3-custom-install.sh && \
	chmod +x $MOUNTPOINT/ENV3-custom-install.sh
	chroot $MOUNTPOINT ./ENV3-custom-install.sh && \
	chmod -x $MOUNTPOINT/ENV3-custom-install.sh
elif ! bash -n ../custom/ENV3-custom-install.sh ; then
	echo "Syntax error in ./ENV3-custom-install.sh detected. Skipping, but continuing ..."
	mv $MOUNTPOINT/ENV3-custom-install.sh $MOUNTPOINT/ENV3-custom-install.broken
	exit 0
else
	echo "No custom install file for ENV3 found, continuing ..."
	exit 0
fi
