#!/bin/bash -e

# inject a sample autostart.sh
echo "Injecting autostart.sh into the data partition ..."
if ! [ -f ../custom/autostart.sh ] ; then
	echo "No custom file found, using template from template directory."
	cp ../templates/autostart.sh ../custom/
fi

echo "Setting executable bit for autostart.sh ..."
chmod +x $MOUNTPOINT/autostart.sh
